### ISSUE TITLE
Conditioning on an end image

### ISSUE THREAD

**Issue by CorentinJ** [Lightricks/LTX-Video#29]
Is it possible to condition the model on an end image? Or is it only operating forward in time?

**Comment by Shecht-ltx** [comment]
@CorentinJ Currently, the model natively supports first-frame conditioning.

However, it is possible to implement end-frame conditioning by using an inference-time in-painting approach, specifically conditioning on the last 8 frames. This works because the last frame in the latent space corresponds to 8 frames in the pixel space.

Looking ahead, we plan to include native support for end-frame conditioning in a future update, making this process more seamless.

**Comment by PeterTucker** [comment]
@Shecht-ltx , any way we could get a workflow example?
