### ISSUE TITLE
Not able to generate good output even with the playground using examples

### ISSUE THREAD

**Issue by nitinmukesh** [Lightricks/LTX-Video#33]
So, I am trying huggingface demo and using the example prompts.
The pre-populated output is very good and if I generate using the same example, it's not even close.

What's the correct way of using it.

**Comment by able2608** [comment]
Could you specify the prompt and setting you use so that we can verify the result and see what could be going wrong?

**Comment by nitinmukesh** [comment]
Sure. It's the first example prompt with default settings

https://huggingface.co/spaces/Lightricks/LTX-Video-Playground
![image](https://github.com/user-attachments/assets/42a76d11-6b3d-4ed0-a520-49bf6caa0eb3)

**Comment by able2608** [comment]
It is possible that the result you are seeing was cherry-picked. Since we do not know the actual seed (in the advanced option section) the sample output was generated with, it might be the culprit (assuming the rest of the settings are the same). You might want to try out other seeds if you're looking to optimize the output, but some source did point out that this model is not as capable as other SOTA models, both open source and closed source ones.
