### ISSUE TITLE
Commercial use in YouTube videos

### ISSUE THREAD

**Issue by qo4on** [Lightricks/LTX-Video#44]
Do I understand correctly that the videos generated by this model and code can be used in my YouTube videos without any restrictions?

**Comment by Shecht-ltx** [comment]
@qo4on 

Thank you for your question! To clarify:
 
1. The LTX Video model itself is licensed under the Rail-M license, which is strictly for research and academic use. This means content generated with the model cannot be used for commercial purposes, including monetized YouTube videos.
 
2. The custom nodes in ComfyUI are licensed under the Apache license, which allows for commercial use. However, since the LTXV model is under the Rail-M license, the restriction on commercial use still applies when using the model, regardless of the licensing of the nodes.
 
We hope this clears things up.
