### ISSUE TITLE
Is there any plan to support fine-tuning?

### ISSUE THREAD

**Issue by ootsuka-repos** [Lightricks/LTX-Video#7]
Both the performance and quality are amazing. Thank you!

I have a few questions:

Is the input size of 768x512 fixed?
Are there any plans for SFT or LoRA training in the future?

**Comment by SAT431** [comment]
you have choice to choose different resolutions. i found on comfyui
![image](https://github.com/user-attachments/assets/1f8e423c-b6c6-4672-ae11-ff21bb3643a3)

**Comment by FDoKE** [comment]
+1 any plans to release training pipeline in near future?

**Comment by horsten** [comment]
If anyone has a fine-tuning pipeline they'd like to share I'd appreciate it. Otherwise I might have a play, I only just got the model today and played a bit, so I don't know for sure, but from a brief look at the code it doesn't look like there's anything too outlandish and there's some support for LoRA in there already, so I'd be surprised if it doesn't arrive soon.

**Comment by radna0** [comment]
Any updates on this?

**Comment by Kvento** [comment]
+1

**Comment by eisneim** [comment]
I've successfully trained LTX image to video lora here: [eisneim/ltx_lora_training_i2v_t2v](https://github.com/eisneim/ltx_lora_training_i2v_t2v) @ootsuka-repos @Kvento @radna0 

![Image](https://github.com/user-attachments/assets/32e436a0-130f-42d2-9a45-9d0b97b3f09b)
https://github.com/user-attachments/assets/602152a1-e3d5-45ef-96e0-5d49f2d70a49
